# Generated by Django 4.1.6 on 2023-02-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='myuser',
            name='telegramUserId',
            field=models.IntegerField(default=486151796),
            preserve_default=False,
        ),
    ]
