# Generated by Django 4.1.6 on 2023-02-28 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbotapp', '0003_alter_tguserids_name'),
        ('users', '0002_remove_myuser_phonenumber_myuser_telegramuserid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='telegramUserId',
        ),
        migrations.AddField(
            model_name='myuser',
            name='tgUserName',
            field=models.ForeignKey(default='JohnyMelon', on_delete=django.db.models.deletion.CASCADE, to='tgbotapp.tguserids', to_field='name'),
            preserve_default=False,
        ),
    ]
