# Generated by Django 4.1.6 on 2023-02-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_tgusername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='tgUserName',
            new_name='tgUser',
        ),
    ]
