# Generated by Django 4.1.6 on 2023-02-16 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskParent',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='task',
            name='taskStartTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='userId',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
