# Generated by Django 4.1.7 on 2023-02-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0002_task_taskparent_task_taskstarttime_task_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskParent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskStartTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
