# Generated by Django 4.1.6 on 2023-02-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbotapp', '0002_alter_tguserids_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguserids',
            name='name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
